### ISSUE TITLE
ImportError: No module named tkinter

### ISSUE THREAD

**Issue by edouard-lopez** [guillaumevincent/clean-git#1]
I installed it with through `pip`

    sudo pip install cleangit

And got

```
$ clean-git 
Traceback (most recent call last):
  File "/usr/local/bin/clean-git", line 3, in <module>
    from cleangit import main
  File "/usr/local/lib/python2.7/dist-packages/cleangit/main.py", line 5, in <module>
    import tkinter
ImportError: No module named tkinter
```

I got `python3-tk` and `python-tk` packages already installed.

**Comment by edouard-lopez** [comment]
I was able to run the app by cloning the repo and run

    git clone git@github.com:guillaumevincent/clean-git.git
    cd clean-git
    python3.5 clean-git

But that not really helpful, after reading [ImportError: No module named tkinter](http://askubuntu.com/a/629173/22343) on stackoverflow, I uninstall and reinstall with `pip3` as `Tkinter` as been rename `tkinter` in Python 3:

```
sudo pip uninstall cleangit
sudo pip3  install cleangit
cleangit 
```
